### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by gvx111** [OrchardCMS/Brochard#26]
When i Running .Web getting some errors.
<pre>
Could not load file or assembly 'OrchardVNext.Setup' or one of its dependencies. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
</pre> 
<b> also same error on OrchardVNext.Demo </b>
Both solution exiting in Modules folder

**Comment by Jetski5822** [comment]
Hmmm most odd, Can you do, "dnvm list"?

**Comment by gvx111** [comment]
<pre>
Active Version           Runtime Architecture Location                    Alias
------ -------           ------- ------------ --------                    -----
       1.0.0-beta4       clr     x64          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\Givi\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\Givi\.dnx\runtimes
  *    1.0.0-beta5-12103 clr     x86          C:\Users\Givi\.dnx\runtimes de...
</pre>

**Comment by Jetski5822** [comment]
Hmmmm - It might be the version of the framework you are using.

Try doing a "dnvm upgrade -u"

if you have compilation issues, let me know.

**Comment by gvx111** [comment]
same problem 
<pre>
System.MissingMethodException
Method not found: 'Microsoft.CodeAnalysis.PortableExecutableReference Microsoft.CodeAnalysis.AssemblyMetadata.GetReference(Microsoft.CodeAnalysis.DocumentationProvider, System.Collections.Immutable.ImmutableArray`1<System.String>, Boolean, System.String, System.String)'.
C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\Extensions\Loaders\DynamicExtensionLoader.cs
Line 49:  
Line 50:              using (_loaderContainer.AddLoader(new ExtensionAssemblyLoader(plocation, _serviceProvider))) {
Line 51:                  var assembly = Assembly.Load(new AssemblyName(descriptor.Id));
Line 52:  
Line 53:                  Logger.Information("Loaded referenced extension \"{0}\": assembly name=\"{1}\"", descriptor.Name, assembly.FullName);
 at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef) 
at OrchardVNext.Environment.Extensions.Loaders.DynamicExtensionLoader.Load(ExtensionDescriptor descriptor) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\Extensions\Loaders\DynamicExtensionLoader.cs:line 51
at OrchardVNext.Environment.Extensions.ExtensionManager.BuildEntry(ExtensionDescriptor descriptor) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\Extensions\ExtensionManager.cs:line 133
at OrchardVNext.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\Extensions\ExtensionManager.cs:line 92
OrchardVNext.OrchardException
Error while loading extension 'OrchardVNext.Setup'.
at OrchardVNext.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\Extensions\ExtensionManager.cs:line 96
at OrchardVNext.Environment.Extensions.ExtensionManager.<LoadFeatures>b__12_0(FeatureDescriptor descriptor) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\Extensions\ExtensionManager.cs:line 78
at System.Linq.Enumerable.WhereSelectEnumerableIterator<TSource, TResult>.MoveNext() 
at System.Linq.Buffer<TElement>..ctor(IEnumerable<TElement> source) 
at System.Linq.Enumerable.ToArray<TSource>(IEnumerable<TSource> source) 
at OrchardVNext.Environment.Extensions.ExtensionManager.LoadFeatures(IEnumerable<FeatureDescriptor> featureDescriptors) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\Extensions\ExtensionManager.cs:line 77
at OrchardVNext.Environment.ShellBuilders.CompositionStrategy.Compose(ShellSettings settings, ShellDescriptor descriptor) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\ShellBuilders\CompositionStrategy.cs:line 37
at OrchardVNext.Environment.ShellBuilders.ShellContextFactory.OrchardVNext.Environment.ShellBuilders.IShellContextFactory.CreateSetupContext(ShellSettings settings) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\ShellBuilders\ShellContextFactory.cs:line 80
at OrchardVNext.Environment.DefaultOrchardHost.CreateShellContext(ShellSettings settings) in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\DefaultOrchardHost.cs:line 34
at OrchardVNext.Environment.OrchardContainerMiddleware.<Invoke>d__4.MoveNext() in C:\Users\Givi\Desktop\Brochard-master\src\OrchardVNext\Environment\OrchardContainerMiddleware.cs:line 31
--- exception rethrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext() 
--- exception rethrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass29_0.<<Start>b__0>d.MoveNext() 
--- exception rethrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__11.MoveNext() 
--- exception rethrown --- 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.<ProcessRequestAsyncImpl>d__11.MoveNext() 
--- exception rethrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.<InvokeProcessRequestAsyncImpl>d__5.MoveNext()
</pre>

**Comment by Jetski5822** [comment]
Here is mine,.

```
D:\Brochard\src\OrchardVNext.Web>dnvm list

Active Version           Runtime Architecture Location                        Alias
------ -------           ------- ------------ --------                        -----
       1.0.0-beta4       clr     x64          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta5-12021 clr     x86          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta6-11944 clr     x86          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta6-12032 clr     x86          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta6-12114 clr     x86          C:\Users\Nicholas\.dnx\runtimes
       1.0.0-beta6-12120 clr     x86          C:\Users\Nicholas\.dnx\runtimes
  *    1.0.0-beta6-12216 clr     x86          C:\Users\Nicholas\.dnx\runtimes default
```

However, there might be compilation issues with tip - I have a version compiling locally, but I am in the middle of switching the IoC container out and have a blocker with Autofac at the moment.

I can push it to a branch... but there is an issue with views at the moment.

**Comment by gvx111** [comment]
can you add me in skype?

**Comment by Jetski5822** [comment]
Jetski5822

**Comment by Jetski5822** [comment]
resolved offline
