### ISSUE TITLE
Running bug

### ISSUE THREAD

**Issue by alexbocharov** [OrchardCMS/Brochard#33]
PS D:\Repositories\Brochard\src\OrchardVNext.Web> dnx . web
Initialize Host
Host Initialized
LogLevel: Information, EventId: 0, State: Start, Exception: , Formatter: System.Func`3[System.Object,System.Exception,System.String], LoggerName: Microsoft.Net.Http.Server.WebListener, Scope:
LogLevel: Information, EventId: 0, State: Listening on prefix: http://local.orchardvnext.test1.com:80/, Exception: , Formatter: System.Func`3[System.Object,System.Exception,System.String], LoggerName: Microsoft.Net.Http.Server.WebListener, Scope:
LogLevel: Error, EventId: 0, State: Start, Exception: Microsoft.Net.Http.Server.WebListenerException (0x80004005): The process cannot access the file because it is being used by another process
   at Microsoft.Net.Http.Server.UrlPrefixCollection.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.Net.Http.Server.UrlPrefixCollection.RegisterAllPrefixes()
   at Microsoft.Net.Http.Server.WebListener.Start(), Formatter: System.Func`3[System.Object,System.Exception,System.String], LoggerName: Microsoft.Net.Http.Server.WebListener, Scope:
Microsoft.Net.Http.Server.WebListenerException (0x80004005): The process cannot access the file because it is being used by another process
   at Microsoft.Net.Http.Server.UrlPrefixCollection.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.Net.Http.Server.UrlPrefixCollection.RegisterAllPrefixes()
   at Microsoft.Net.Http.Server.WebListener.Start()
   at Microsoft.AspNet.Server.WebListener.MessagePump.Start(Func`2 app)
   at Microsoft.AspNet.Server.WebListener.ServerFactory.Start(IServerInformation server, Func`2 app)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
PS D:\Repositories\Brochard\src\OrchardVNext.Web>

**Comment by alexbocharov** [comment]
dnvm: 1.0.0-beta7-12290 clr x86

**Comment by Jetski5822** [comment]
Hmmm are you sure you didnt have he site kicked up twice? 

"The process cannot access the file because it is being used by another process"

**Comment by alexbocharov** [comment]
Rebooting helped
