### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gvx111** [OrchardCMS/Brochard#35]
error   : [Microsoft.AspNet.Server.WebListener.MessagePump] ProcessRequestAsync
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNet.Routing.IRouteBuilder' while attempting to activate 'OrchardVNext.Hosting.Web.Routing.Routes.RoutePublisher'.
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.<GetService>b__7_0(Type key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at OrchardVNext.Hosting.ShellBuilders.ShellContainerFactory.WrappingServiceProvider.GetService(Type serviceType) in D:\My Projects\ITN.TravelSoftware\ITN.TS.Framework\src\OrchardVNext.Hosting\ShellBuilders\ShellContainerFactory.cs:line 114
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at OrchardVNext.Hosting.ShellBuilders.ShellContextFactory.OrchardVNext.Hosting.ShellBuilders.IShellContextFactory.CreateSetupContext(ShellSettings settings) in D:\My Projects\ITN.TravelSoftware\ITN.TS.Framework\src\OrchardVNext.Hosting\ShellBuilders\ShellContextFactory.cs:line 90
   at OrchardVNext.Hosting.DefaultOrchardHost.CreateShellContext(ShellSettings settings) in D:\My Projects\ITN.TravelSoftware\ITN.TS.Framework\src\OrchardVNext.Hosting\DefaultOrchardHost.cs:line 36
   at OrchardVNext.Hosting.OrchardContainerMiddleware.<Invoke>d__10.MoveNext() in D:\My Projects\ITN.TravelSoftware\ITN.TS.Framework\src\OrchardVNext.Hosting.Web\OrchardContainerMiddleware.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass29_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Server.WebListener.MessagePump.<ProcessRequestAsync>d__23.MoveNext()

**Comment by Jetski5822** [comment]
Can you do 'dnvm list' for me? and show me what version you are using?

**Comment by Jetski5822** [comment]
Fixed in https://github.com/OrchardCMS/Brochard/commit/9cb7acd32b0badb27a1f203f958e39773e69cbef
